import type { NextPage } from 'next';
import { useAuthenticator } from '@aws-amplify/ui-react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { user, signOut } = useAuthenticator((context) => [context.user]);

  console.log(user);
  const userSession = user.getSignInUserSession();
  console.log(userSession?.getIdToken());
  console.log(userSession?.getRefreshToken());
  console.log(userSession?.getAccessToken());

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          <button onClick={signOut}>Sign out</button>
        </p>
      </main>
    </div>
  );
};

export default Home;
